# Build settings
markdown: rdiscount
highlighter: pygments

# Site settings
title: "Paul's Blog"
description: > # this means to ignore newlines until "email:"
   My Personal Blog about Pogramming, Math, Science, and Travel

email: pheinenjr@gmail.com
#blog logo
logo: "/assets/images/haskellSmall.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Paul Heinen'
author: 'Paul Heinen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://v3nturetheworld.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/v3nturetheworld
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/v3nturetheworld
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
